# Generated by Django 5.0.3 on 2024-05-06 19:06

import cadastros.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_rename_senha_usuario_senha_do_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Departamento',
            field=models.CharField(choices=cadastros.models.Usuario.get_choices, max_length=100),
        ),
    ]
